project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"pull_request_title": "New Crowdin Translations"
"pull_request_labels": ["translation"]

files:
  [
    {
      "source": "/bulbbot.Babelz/locales/en.yml",
      "translation": "/bulbbot.Babelz/locales/%locale%.yml",
    },
  ]
