[package]
name = "babelz"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "babelz"
path = "src/lib.rs"

[[bin]]
name = "babelz"
path = "src/bin/babelz.rs"
