name: Bulbbot Gateway Validation

on:
  push:
    paths:
      - "./Bulbbot.Gateway/**"
    branches:
      - master
  pull_request:
    paths:
      - "./Bulbbot.Gateway/**"
    types: [opened, edited, reopened]

jobs:
  test:
    defaults:
      run:
        working-directory: ./Bulbbot.Gateway
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  fmt:
    defaults:
      run:
        working-directory: ./Bulbbot.Gateway
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    defaults:
      run:
        working-directory: ./Bulbbot.Gateway
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy -- -D warnings
