name: Bulbbot Guild Service Validation

on:
  push:
    paths:
      - "bulbbot.GuildService/**"
    branches:
      - master
  pull_request:
    paths:
      - "bulbbot.GuildService/**"
    types: [opened, edited, reopened]

jobs:
  test:
    defaults:
      run:
        working-directory: ./bulbbot.GuildService
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --verbose

  fmt:
    defaults:
      run:
        working-directory: ./bulbbot.GuildService
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    defaults:
      run:
        working-directory: ./bulbbot.GuildService
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy --all -- -D warnings
